apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component
images:
- name: davidschmidt38/dsc-hgui-ufe
  newName: davidschmidt38/dsc-hgui-ufe
  newTag: 1.0.2  #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú
- name: davidschmidt38/dsc-hgui-webapi
  newName: davidschmidt38/dsc-hgui-webapi
  newTag: 1.0.1

replacements:
 - targets:
   - select:
         group: fe.milung.eu
         version: v1
         kind: WebComponent
         name: dsc-hgui-ufe
     fieldPaths:
         - spec.hash-suffix
   source:
     version: v1
     kind: Deployment
     name:  dsc-hgui-ufe-deployment
     fieldPath: spec.template.spec.containers.0.image
     options:
         delimiter: ':'
         index: 1