apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsc-hgui-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /dsc-hgui-openapi
            - name: BASE_URL
              value: /dsc-hgui-openapi-ui